spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie-store
    username: mysql
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 7070
  servlet:
    context-path: /api

movie-store:
  security:
    secret-key: movieStoreSecretKey
    token-validity: 86400000
