version: "3.8"

services:
  store-db:
    container_name: store-db
    image: mysql:8.0.20
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: movie-store
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    restart: unless-stopped
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
    networks:
      - store-network
#  api:
#    container_name: movie-store-api
#    image: movie-store-0.0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    restart: on-failure
#    depends_on:
#      - postgres
#    networks:
#      - store-network

volumes:
  mysql-init:
    driver: local
  mysql-data:
    driver: local
#    external: true

networks:
  store-network:
    driver: bridge
